name: Build Application

on:
  push:
    paths:
      - 'news-app/**'

env:
  app: ./news-app
  AZURE_WEBAPP_NAME:  news-app-914

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ${{ env.app }}/pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.app }}

      - name: Check application
        run: pnpm check
        working-directory: ${{ env.app }}

      - name: Audit application
        run: pnpm audit --audit-level moderate
        working-directory: ${{ env.app }}

      - name: Build application
        run: pnpm build
        working-directory: ${{ env.app }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: news-app
          path: |
            ${{ env.app }}/build

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: news-app
          path: build

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: build

